import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src = Glob('*.c')


if GetDepend(['USING_ELEC_DEV']):
    src += Glob(r'elec_thread\*.c')
    src += Glob(r'elec_drv\*.c')
    src += Glob(r'elec_protocol\*.c')

    CPPPATH += [cwd + '/elec_thread']
    CPPPATH += [cwd + '/elec_drv']
    CPPPATH += [cwd + '/elec_protocol']

if GetDepend(['ELEC_DEV_CCO_MODE']):
    src += Glob(r'elec_cco_api\*.c')
    src += Glob(r'elec_cco_app\*.c')
    CPPPATH += [cwd + '/elec_cco_api']
    CPPPATH += [cwd + '/elec_cco_app']

if GetDepend(['ELEC_DEV_METER_MODE']):
    src += Glob(r'elec_meter_api\*.c')
    CPPPATH += [cwd + '/elec_meter_api']

if GetDepend(['ELEC_DEV_CTRLER_MODE']):
    src += Glob(r'elec_ctrler_api\*.c')
    CPPPATH += [cwd + '/elec_ctrler_api']
group = DefineGroup('elec_module', src, depend = ['USING_ELEC_DEV'], CPPPATH = CPPPATH)

Return('group')