Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = []

if GetDepend(['RT_USING_PIN']):
    src += ['drv_gpio.c']

if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_usart.c']

if GetDepend(['RT_USING_PWM']):
    src += ['drv_pwm.c']

if GetDepend(['RT_USING_ADC']):
    src += Glob('drv_adc.c')

if GetDepend(['RT_USING_DAC']):
    src += Glob('drv_dac.c')

if GetDepend('RT_USING_RTC'):
    src += ['drv_rtc.c']

if GetDepend(['RT_USING_WDT']):
    src += ['drv_wdt.c']

if GetDepend(['RT_USING_I2C']):
    if GetDepend(['RT_USING_I2C_BITOPS']):
        src += ['drv_soft_i2c.c']
    else:
        src += ['drv_hard_i2c.c']

if GetDepend(['RT_USING_SPI']):
    if GetDepend(['RT_USING_SPI_BITOPS']):
        src += ['drv_soft_spi.c']
    else:
        src += ['drv_hard_spi.c']

if GetDepend(['BSP_USING_ON_CHIP_FLASH']):
    src += ['drv_flash.c']

if GetDepend(['RT_USING_HWTIMER']):
    src += ['drv_hwtimer.c']

path = [cwd]

group = DefineGroup('HAL_Drivers', src, depend = [''], CPPPATH = path)

Return('group')
