Import('RTT_ROOT')
Import('rtconfig')
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

path = [cwd]
src = Glob("*.c")

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

objs += group
Return('objs')

