#ifndef _MANAGER_MODULE_H_
#define _MANAGER_MODULE_H_

enum manager_tasks_identification
{
    MANAGER_MODULE_DEFAULT = 0,
    MANAGER_WIOTA_INDENTIFICATION,
    MANAGER_LOGIC_INDENTIFICATION,
    MANAGER_CUSTOM_INDENTIFICATION
};

#endif
