# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src = Glob('*.c')
src += ['crt0.flash.S']
CPPPATH = [cwd]

group = DefineGroup('Board', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
