from building import *

cwd = GetCurrentDir()

src = []

src_cbor = Glob("cbor/*.c")
src_coding = Glob("coding/*.c")
src_fastlz = Glob("fastlz/*.c")
src_json =Glob("cJSON/*.c")


src += src_coding
src += src_fastlz


path = []

path += [cwd + '/coding']
path += [cwd + '/fastlz']


group = DefineGroup('codec', src, depend = [''], CPPPATH = path)

Return('group')