from building import *

cwd = GetCurrentDir()

path = [cwd + '/app/include']
path += [cwd + '/app/test']

src = Glob('app/test/*.c')

if GetDepend(['RT_USING_AT','UC8288_MODULE']):
    src += ['at/at_wiota.c', 'at/at_boot.c', 'at/at_wiota_auto_manager.c']
    path += [cwd + '/at']

    if GetDepend(['UC8288_FACTORY']):
        src += ['at/at_factory.c']

lib = ['libwin_wiota_dev']
libpath = [cwd + '/lib']

group = DefineGroup('PS', src, depend = [''], CPPPATH = path, LIBS = lib, LIBPATH = libpath)

Return('group')
