# for module compiling
import os
Import('RTT_ROOT')
from building import *

cwd  = GetCurrentDir()

src = []
path = []

if GetDepend(['WIOTA_APP_DEMO']):
    path += [cwd]
    src += Glob('*.c')

group = DefineGroup('customer', src, depend = [''], CPPPATH = path)

Return('group')
